name: Pack Nuget

on:
  push:
    branches: [ "action/pack" ]
  pull_request:
    branches: [ "action/pack" ]

jobs:
  nuget:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Nuget Ursa
        run: dotnet pack ./src/Ursa -o ./nugets

      - name: Nuget Ursa.Themes.Semi
        run: dotnet pack ./src/Ursa.Themes.Semi -o ./nugets

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: nugets
          path: ./nugets
